config/routes.rb
Rails.application.routes.draw do

  post '/comments/create' => 'comments#create'

  get 'events/index'

  get 'events/:id' => "events#show"

  post '/events' => "events#create"

  get 'events/:id/edit' => 'events#edit'

  post 'events/:id/update' => 'events#update'

  post 'events/update'

  get 'events/:id/destroy' => "events#destroy"

  root "users#index"

  get '/signout' => "sessions#destroy"

  resources :attendees, :only => [:create, :destroy]

  get '/attendees/:id/destroy' => 'attendees#destroy'

  resources :events

  resources :users

  resources :sessions, :only => [:create, :destroy]

  post '/users' => "users#create"

  get 'users/:id/edit' => 'users#edit'

  post 'users/:id/update' => 'users#update'

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :comment, :presence => true, :length => { :in => 8..500 }
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :attendees, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  validates :name, :date, :city, :presence => true
  validate :date_cannot_be_in_the_past

  def date_cannot_be_in_the_past
  	if date.present? && date < Date.today
  		errors.add(:date, "can't be in the past")
  	end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :events, :dependent => :destroy
	has_many :attendees, :dependent => :destroy
	has_many :comments, :dependent => :destroy

	attr_accessor :password, :password_confirmation

	EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	validates :first_name,  
			  :presence => true, 
			  :length => { :in => 2..30 }
	validates :last_name, 
			  :presence => true, 
			  :length => { :in => 2..30 }
	validates :email, 
			  :presence => true, 
			  :uniqueness => { :case_sensitive => false },
			  :format => { :with => EMAIL_REGEX }
	validates :city, 
			  :presence => true
	validates :password, 
			  :presence => true,
			  :confirmation => true,
			  :length => { :in => 8..100 }
	validates :password_confirmation, 
			  :presence => true

	#before the user gets added to DB, run this function
	before_save :encrypt_password 

	#this method encrypts the user's unencrypted login attempt 
	#returns true if the password is a match 
	def has_password?(submitted_password)
		self.encrypted_password == encrypt(submitted_password)
	end

	#class method that checks whethere the user's email and submitted password are valid 
	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end

	private
		def encrypt_password
			# generate a unique salt if it's a new user 
			# self.password uses the attr_accessor we defined above to allow me to grab the inputed password 
			self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{self.password}") if self.new_record?

			# encrypt the password and store that in the encrypted_password field 
			self.encrypted_password = encrypt(self.password) #this self.password is what's in the post data
		end

		def encrypt(password)
			Digest::SHA2.hexdigest("#{self.salt}--#{password}")
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  def create
  	@attendee = Attendee.new(attendee_params)
  	@attendee.save
  	redirect_to :back
  end

  def destroy
  	Attendee.find(params[:id]).destroy
  	redirect_to :back
  end

  private 

  def attendee_params
  	params.require(:attendee).permit(:user_id, :event_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@comment = Comment.new(comment_params) 
  	if @comment.save
  		flash[:success] = 'Comment Posted!'
  		redirect_to :back
  	else
  		flash[:errors] = @comment.errors.full_messages
  		redirect_to :back
  	end
  end

  private 

  def comment_params
  	params.require(:comment).permit(:comment, :user_id, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
    @event = Event.find(params[:id])
    @attendees = Attendee.all #where("event_id = @event.id")
    @counter = Attendee.where(event_id: @event.id).count
    @user = User.find(session[:user_id])
    @comments = Comment.all
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = 'Event was successfully created!' 
      redirect_to :back
    else
      flash[:errors] = @event.errors.full_messages 
      redirect_to :back
    end
  end

  def edit
    @event = Event.find(params[:id])
    @user = User.find(session[:user_id])
  end

  def update
    Event.find(params[:id]).update( event_params )
    flash[:success] = 'Event updated!'
    redirect_to :back
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to :back
  end

  private 

  def event_params
    params.require(:event).permit(:name, :date, :city, :state, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	#this references the function we made in user.rb
  	user = User.authenticate(params[:session][:email], params[:session][:password])
  	if user.nil?
  		flash[:error] = 'Invalid Login Credentials'
  		#if there is an error, redirect back to login
  		redirect_to '/'
  	else 
  		sign_in user
  		redirect_to user
  	end
  end

  def destroy
  	sign_out
  	redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index	
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save 
  		flash[:success] = 'User was successfully created!'
  		redirect_to '/' 
  	else
  		flash[:errors] = @user.errors.full_messages
  		redirect_to '/'
  	end
  end

  def show 
  	@user = User.find(params[:id])
  	@events = Event.all
    @attendees = Attendee.all
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	User.find(params[:id]).update( user_params )
  	redirect_to user_path
  end

  private 

  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :city, :state, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end
  
  # setter method
  def current_user=(user)
    @current_user = user
  end

  # getter method
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user 
  end

  def deny_access
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

end

app/helpers/states_helper.rb
module StatesHelper

def us_states 
	[
    ['AK', 'AK'],
    ['AL', 'AL'],
    ['AR', 'AR'],
    ['AZ', 'AZ'],
    ['CA', 'CA'],
    ['CO', 'CO'],
    ['CT', 'CT'],
    ['DC', 'DC'],
    ['DE', 'DE'],
    ['FL', 'FL'],
    ['GA', 'GA'],
    ['HI', 'HI'],
    ['IA', 'IA'],
    ['ID', 'ID'],
    ['IL', 'IL'],
    ['IN', 'IN'],
    ['KS', 'KS'],
    ['KY', 'KY'],
    ['LA', 'LA'],
    ['MA', 'MA'],
    ['MD', 'MD'],
    ['ME', 'ME'],
    ['MI', 'MI'],
    ['MN', 'MN'],
    ['MO', 'MO'],
    ['MS', 'MS'],
    ['MT', 'MT'],
    ['NC', 'NC'],
    ['ND', 'ND'],
    ['NE', 'NE'],
    ['NH', 'NH'],
    ['NJ', 'NJ'],
    ['NM', 'NM'],
    ['NV', 'NV'],
    ['NY', 'NY'],
    ['OH', 'OH'],
    ['OK', 'OK'],
    ['OR', 'OR'],
    ['PA', 'PA'],
    ['RI', 'RI'],
    ['SC', 'SC'],
    ['SD', 'SD'],
    ['TN', 'TN'],
    ['TX', 'TX'],
    ['UT', 'UT'],
    ['VA', 'VA'],
    ['VT', 'VT'],
    ['WA', 'WA'],
    ['WI', 'WI'],
    ['WV', 'WV'],
    ['WY', 'WY']
  ]
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendees/create.html.erb
<h1>Attendees#create</h1>
<p>Find me in app/views/attendees/create.html.erb</p>

app/views/attendees/destroy.html.erb
<h1>Attendees#destroy</h1>
<p>Find me in app/views/attendees/destroy.html.erb</p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/events/edit.html.erb
<h1>Update <%= @event.name %></h1>
<div class="links">
<a href="/users/<%= @user.id %>">Events Dashboard</a> | 
<a href="/signout">Logout</a>
</div>
<% if flash[:success] %>
  <p class="green"><%= flash[:success] %></p>
<% end %>
<%= form_for( :event, :url => { :action => :update, :event_id => @event.id } ) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <br />
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <br />
  <div class="field">
	<%= f.label :city %><br />
	<%= f.text_field :city %>
  </div>
  <br />
  <div class="field">
	<%= f.label :state %><br />
	<%= f.select(:state, options_for_select(us_states, 'WA')) %>
  </div>
  <%= f.hidden_field :user_id, :value => @user.id %>
  <br />
  <div class="actions">
    <%= f.submit "Update Event" %>
  </div>
<% end %>

app/views/events/index.html.erb
<h1>Welcome</h1>
<p>You are logged in!</p>
<a href="/signout">Logout</a>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<div class="links">
<a href="/users/<%= @user.id %>">Events Dashboard</a> | 
<a href="/signout">Logout</a>
</div>
<div class="discussion">
	<h3>Discussion about this event:</h3>
	<div class="feed">
		<% @comments.each do |comment| if @event.id == comment.event.id %>
			<p class="center"><%= comment.user.first_name %> says: <%= comment.comment %></p>
			<p class="center">____________________________</p>
		<% end %>
		<% end %>
	</div>
	<% if flash[:errors] %>
		<% flash[:errors].each do |error| %>
			<p class="red"><%= error %></p>
		<% end %>
	<% end %>
	<% if flash[:success] %>
		<p class="green"><%= flash[:success] %></p>
	<% end %>
	<h4>Add Comment:</h4>
	<%= form_for( :comment, :url => comments_create_path) do |f| %>
		<%= f.text_area :comment %>
		<%= f.hidden_field :user_id, :value => @user.id %>
		<%= f.hidden_field :event_id, :value => @event.id %><br />
		<%= f.submit "Post Comment" %>
	<% end %>
</div>
<br />
<ul class="event">
	<li><h3>Host: <%= @event.user.first_name %> <%= @event.user.last_name %></h3></li>
	<li><h3>Date: <%= @event.date.to_formatted_s(:long_ordinal) %></h3></li>
	<li><h3>Location: <%= @event.city %> <%= @event.state %></h3></li>

	<li><h3>People joining the event: <%= @counter %></h3></li>

</ul>
<br />
<table>
	<thead>
		<th>Name</th>
		<th>City</th>
		<th>State</th>
	</thead> 
	<tbody>
		<% @attendees.each do |attendee| if @event.id == attendee.event.id %>
		<tr>
			<td><%= attendee.user.first_name %> <%= attendee.user.last_name %></td>
			<td><%= attendee.user.city %></td>
			<td><%= attendee.user.state %></td>
		</tr>
		<% end %>
		<% end %>
	</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeltReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
<body>
	<script type="text/javascript">
		$(document).ready(function(){
			
		});
	</script>

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>
<div class="links">
<a href="<%= user_path %>">Events Dashboard</a> | 
<a href="/signout">Logout</a>
</div>
<br />
<%= form_for @user do |f| %>

<div class="field">
	<%= f.label :first_name %><br />
	<%= f.text_field :first_name %>
</div>
<br />
<div class="field">
	<%= f.label :last_name %><br />
	<%= f.text_field :last_name %>
</div>
<br />
<div class="field">
	<%= f.label :email %><br />
	<%= f.text_field :email %>
</div>
<br />
<div class="field">
	<%= f.label :city %><br />
	<%= f.text_field :city %>
</div>
<br />
<div class="field">
	<%= f.label :state %><br />
	<%= f.select(:state, options_for_select(us_states, "WA")) %>
</div>
<br />
<p>*Password should be at least 8 characters</p>
<div class="field">
	<%= f.label :password %><br />
	<%= f.password_field :password %>
</div>
<br />
<div class="field">
	<%= f.label "Confirm Password" %><br />
	<%= f.password_field :password_confirmation %>
</div>
<br />
<div class="actions">
    <%= f.submit "Update Records" %>
 </div>

<% end %>

app/views/users/index.html.erb
<h1 class="center">Welcome to Event meetup!</h1>

<div class="reg">
<h2>Register</h2>
<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
		<p class="red"><%= error %></p>
	<% end %>
<% end %>
<% if flash[:success] %>
	<p><%= flash[:success] %></p>
<% end %>
<%= form_for @user do |f| %>

<div class="field">
	<%= f.label :first_name %><br />
	<%= f.text_field :first_name %>
</div>
<br />
<div class="field">
	<%= f.label :last_name %><br />
	<%= f.text_field :last_name %>
</div>
<br />
<div class="field">
	<%= f.label :email %><br />
	<%= f.text_field :email %>
</div>
<br />
<div class="field">
	<%= f.label :city %><br />
	<%= f.text_field :city %>
</div>
<br />
<div class="field">
	<%= f.label :state %><br />
	<%= f.select(:state, options_for_select(us_states, "WA")) %>
</div>
<br />
<p>*Password should be at least 8 characters</p>
<div class="field">
	<%= f.label :password %><br />
	<%= f.password_field :password %>
</div>
<br />
<div class="field">
	<%= f.label "Confirm Password" %><br />
	<%= f.password_field :password_confirmation %>
</div>
<br />
<div class="actions">
    <%= f.submit "Register" %>
 </div>

<% end %>
</div>
<!-- End of Registration -->
<!--#######################################################################-->
<div class="log">
<h2>Log In</h2>
<%= flash[:error] %>
<%= form_for( :session, :url => sessions_path ) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <br />
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

</div>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.first_name %>!</h1>
<div class="links"> 
<a href="/users/<%= @user.id %>/edit">Edit my profile</a> | 
<a href="/signout">Logout</a>
</div>
<br />
<h3 class="formHead">Here are the events in your state:</h3>
<table class="middle">
	<thead>
		<th>Name</th>
		<th>Date</th>
		<th>Location</th>
		<th>Host</th>
		<th>Action/Status</th>
	</thead>
	<tbody>
		<% @events.each do |event| %>
			<% if event.state == @user.state %> <!-- If the event is in the users state -->
		<tr>
			<td><a href="/events/<%= event.id %>"><%= event.name %></a></td>
			<td><%= event.date.to_formatted_s(:long_ordinal) %></td>
			<td><%= event.city %></td> 
			<td><%= event.user.first_name %></td>
			<td>
				<% if event.user.id == @user.id %> <!-- If the user made the event -->
					<a href="/events/<%= event.id %>/edit">Edit</a> | <a href="/events/<%= event.id %>/destroy">Delete</a>
				<% end %>										
				<% if event.user.id != @user.id %> <!-- The user DID NOT make the event -->
					<%= form_for( :attendee, :url => attendees_path ) do |f| %>
						<%= f.hidden_field :user_id, :value => @user.id %>
						<%= f.hidden_field :event_id, :value => event.id %>
						<%= f.submit "Join Event" %>
					<% end %>
				<% end %>
				<% @attendees.each do |attendee| %>
				<% if event.user.id != @user.id && @user.id == attendee.user.id && event.id == attendee.event.id %>
					<p class="joined">Joined</p>
					<a href="/attendees/<%= attendee.id %>/destroy">Cancel</a>
				<% end %>
				<% end %>
			</td>
		</tr>
		<% end %>
		<% end %>
	</tbody>
</table>

<h3 class="formHead">Here are the events in other states:</h3>
<table class="middle">
	<thead>
		<th>Name</th>
		<th>Date</th>
		<th>Location</th>
		<th>State</th>
		<th>Host</th>
		<th>Action</th>
	</thead>
	<tbody>
		<% @events.each do |event| %>
			<% if event.state != @user.state %> <!-- If the event is NOT in the users state -->
			<tr>
				<td><a href="/events/<%= event.id %>"><%= event.name %></a></td>
				<td><%= event.date.to_formatted_s(:long_ordinal) %></td>
				<td><%= event.city %></td>
				<td><%= event.state %></td>
				<td><%= event.user.first_name %></td>
				<td>
					<% if event.user.id == @user.id %> <!-- If the user made the event -->
						<a href="/events/<%= event.id %>/edit">Edit</a> | <a href="/events/<%= event.id %>/destroy">Delete</a>
					<% end %>

					<% if event.user.id != @user.id %> <!-- If the user didnt make the event -->
						<%= form_for( :attendee, :url => attendees_path ) do |f| %>
							<%= f.hidden_field :user_id, :value => @user.id %>
							<%= f.hidden_field :event_id, :value => event.id %>
							<%= f.submit "Join Event" %>
						<% end %>
					<% end %>
					<% @attendees.each do |attendee| %>
					<% if event.user.id != @user.id && @user.id == attendee.user.id && event.id == attendee.event.id %>
						<p class="joined">Joined</p>
						<a href="/attendees/<%= attendee.id %>/destroy">Cancel</a>
					<% end %>
					<% end %>
				</td> 
			</tr>
			<% end %>
		<% end %>
	</tbody>
</table>
<br />
<div class="eventForm"> <!-- CREATE AN EVENT -->
<h3>Add Event</h3>
<% if flash[:errors] %>
	<% flash[:errors].each do |error| %>
		<p class="red"><%= error %></p>
	<% end %>
<% end %>
<% if flash[:success] %>
	<p class="green"><%= flash[:success] %></p>
<% end %>
<%= form_for( :event, :url => events_path ) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <br />
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <br />
  <div class="field">
	<%= f.label :city %><br />
	<%= f.text_field :city %>
  </div>
  <br />
  <div class="field">
	<%= f.label :state %><br />
	<%= f.select(:state, options_for_select(us_states, "WA")) %>
  </div>
  <%= f.hidden_field :user_id, :value => @user.id %>
  <br />
  <div class="actions">
    <%= f.submit "Add Event" %>
  </div>
<% end %>
</div>